### ISSUE TITLE
missing dependences?

### ISSUE THREAD

**Issue by Elmapul** [shrekshao/glAvatar#1]
Error: Cannot find module 'uglifyjs-webpack-plugin'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/elmapul/Downloads/tests/glAvatar-master/webpack.config.js:4:24)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at requireConfig (/home/elmapul/Downloads/tests/emsdk/node/4.1.1_64bit/lib/node_modules/webpack/bin/convert-argv.js:97:18)
    at /home/elmapul/Downloads/tests/Downloads/emsdk/node/4.1.1_64bit/lib/node_modules/webpack/bin/convert-argv.js:104:17
    at Array.forEach (native)
    at module.exports (/home/elmapul/Downloads/emsdk/node/4.1.1_64bit/lib/node_modules/webpack/bin/convert-argv.js:102:15)
    at /home/elmapul/Downloads/tests/Downloads/emsdk/node/4.1.1_64bit/lib/node_modules/webpack/bin/webpack.js:171:41

**Comment by shrekshao** [comment]
Should fix at the latest master HEAD for now. Thanks for the report
